# Generated by Django 4.1.1 on 2022-09-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_country"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="entrancefee_amount",),
        migrations.RemoveField(model_name="client", name="insurance_amount",),
        migrations.RemoveField(model_name="client", name="membershipfee_amount",),
        migrations.RemoveField(model_name="client", name="sharecapital_amount",),
    ]
