# Generated by Django 4.1.1 on 2022-09-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_client_entrancefee_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("OfficeAdmin", "Can manage all users accounts."),
                    ("LoanOfficer", "Can add client accounts"),
                    ("edit_clients", "Can edit client accounts"),
                    ("view_clients", "Can view client accounts"),
                    ("manage_clients", "Can manage client accounts"),
                )
            },
        ),
    ]
