# Generated by Django 4.1.1 on 2022-09-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("OfficeAdmin", "Can manage all users accounts."),
                    ("Add_user", "Can add user accounts."),
                    ("edit_clients", "Can edit client accounts."),
                    ("view_clients", "Can view client accounts."),
                    ("manage_clients", "Can manage client accounts."),
                )
            },
        ),
    ]
