# Generated by Django 4.1.1 on 2022-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="receipts", name="fixeddeposit_amount",),
        migrations.RemoveField(model_name="receipts", name="group_loan_account",),
        migrations.RemoveField(model_name="receipts", name="member_loan_account",),
        migrations.RemoveField(
            model_name="receipts", name="savingsdeposit_thrift_amount",
        ),
        migrations.RemoveField(model_name="receipts", name="sharecapital_amount",),
        migrations.AddField(
            model_name="payments",
            name="payment_id",
            field=models.CharField(default="qwerty123", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
