# Generated by Django 4.1.1 on 2022-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_receipts_fixeddeposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Paypal", "Paypal"),
                    ("Stripe", "Stripe"),
                    ("Payoneer", "Payoneer"),
                ],
                default="Paypal",
                max_length=25,
            ),
            preserve_default=False,
        ),
    ]
