# Generated by Django 4.1.1 on 2022-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_payments_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="interest_rate",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
